"""Strategy mutation dispatch for the chat co-pilot (§21).

This is the seam every pipeline stage plugs into. When a user override arrives
via chat, apply_intent_to_strategy:
  1. Dispatches to the registered category mutator.
  2. The mutator modifies the Run object IN MEMORY only - no DB writes.
  3. apply_intent_to_strategy commits strategy changes + audit entry atomically.

Adding a new category (e.g., "threshold", "fairness") means registering one
function with @_register("category") - nothing else changes.

Mutator signature:
    async def _(session, run, payload) -> list[StrategyDiff]

The mutator may return [] to signal "no applicable change" (e.g., strategy not
initialized yet, or no-op because the value is already set). This is not an
error - the caller just produces no diff card.
"""

import logging
from collections.abc import Callable, Coroutine
from copy import deepcopy
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from backend.core import audit
from backend.core.database import Run
from backend.models.chat import ChatIntent, PendingIntent, StrategyDiff, UserDirective

logger = logging.getLogger(__name__)

# Decision categories whose overrides are NOT applied as deterministic field
# edits, but recorded as verbatim directives and replayed to the producing agent
# when its step re-runs (so the AI regenerates the decision honouring the human).
# Everything else (threshold, fairness, model_selection) keeps its deterministic
# mutator because those decisions are consumed directly, not regenerated by an LLM.
PRODUCER_REGENERATED_CATEGORIES = frozenset({"preprocessing"})

MutatorFn = Callable[
    [AsyncSession, Run, dict[str, Any]],
    Coroutine[Any, Any, list[StrategyDiff]],
]

_MUTATORS: dict[str, MutatorFn] = {}


def _register(category: str) -> Callable[[MutatorFn], MutatorFn]:
    def decorator(fn: MutatorFn) -> MutatorFn:
        _MUTATORS[category] = fn
        return fn
    return decorator


# ── Category mutators ──────────────────────────────────────────────────────────
# Each mutator: modifies run fields in memory, returns list[StrategyDiff].
# Do NOT call session.begin() here - apply_intent_to_strategy commits everything.


# NOTE: preprocessing overrides are NOT handled by a deterministic field-edit
# mutator. apply_intent_to_strategy routes them to record_directive, which stores
# the human's verbatim instruction and replays it to the preprocessing agent when
# the step re-runs (see PRODUCER_REGENERATED_CATEGORIES). This lets a clinician
# override ANY preprocessing decision in plain language - including multi-column
# requests like "drop both clinical_syndrome and clade" that a single-column
# field edit could not express.


@_register("model_selection")
async def _model_selection_mutator(
    session: AsyncSession, run: Run, payload: dict[str, Any]
) -> list[StrategyDiff]:
    if not run.model_selection:
        return []

    model = payload.get("model")
    if not model:
        return []

    selection = deepcopy(run.model_selection)
    before = selection.get("primary")
    if before == model:
        return []

    selection["primary"] = model
    # Mark the choice as a human override so the training step honours it
    # exactly and never reverts to the leaderboard winner (see
    # tasks.analysis_task.resolve_training_primary).
    selection["primary_source"] = "user_override"
    # Guarantee the chosen model is actually trained/evaluated as a candidate;
    # otherwise the override could name a model the leaderboard never scores.
    candidates = list(selection.get("candidates") or [])
    if model not in candidates:
        candidates.append(model)
        selection["candidates"] = candidates
    run.model_selection = selection

    return [
        StrategyDiff(
            field_path="model_selection.primary",
            before=before,
            after=model,
            summary=f"Changed primary model: {before!r} → {model!r}",
            run_id=run.id,
        )
    ]


@_register("threshold")
async def _threshold_mutator(
    session: AsyncSession, run: Run, payload: dict[str, Any]
) -> list[StrategyDiff]:
    """Override the classification threshold or its business cost matrix.

    Accepts either a direct threshold ("set the threshold to 0.3") or cost-matrix
    weights ("make a false negative cost 10x a false positive"). The config is
    created if the run has none yet, so a user can set the cost matrix before the
    threshold step has run.
    """
    config = deepcopy(run.threshold_config or {})
    diffs: list[StrategyDiff] = []

    threshold = payload.get("threshold")
    if threshold is not None:
        before = config.get("override_threshold")
        if before != float(threshold):
            config["override_threshold"] = float(threshold)
            diffs.append(StrategyDiff(
                field_path="threshold_config.override_threshold",
                before=before, after=float(threshold),
                summary=f"Overrode classification threshold: {before} → {threshold}",
                run_id=run.id,
            ))

    # Cost matrix: accept a nested cost_matrix dict or flat cost_fn / cost_fp keys.
    cost_in = dict(payload.get("cost_matrix") or {})
    for k in ("cost_fn", "cost_fp"):
        if payload.get(k) is not None:
            cost_in[k] = payload[k]
    if cost_in:
        cost_matrix = dict(config.get("cost_matrix") or {})
        before_cm = deepcopy(cost_matrix)
        for k, v in cost_in.items():
            cost_matrix[k] = float(v)
        if cost_matrix != before_cm:
            config["cost_matrix"] = cost_matrix
            diffs.append(StrategyDiff(
                field_path="threshold_config.cost_matrix",
                before=before_cm or None, after=cost_matrix,
                summary=f"Updated cost matrix → {cost_matrix}",
                run_id=run.id,
            ))

    if not diffs:
        return []
    run.threshold_config = config
    return diffs


@_register("fairness")
async def _fairness_mutator(
    session: AsyncSession, run: Run, payload: dict[str, Any]
) -> list[StrategyDiff]:
    """Override the fairness audit's protected attributes.

    Accepts "add age_group to protected attributes" (payload column/value) or a
    full replacement list (protected_columns). Creates fairness_config if absent,
    so the user can request a fairness audit that the agent did not configure.
    """
    config = deepcopy(run.fairness_config or {})
    before = list(config.get("protected_columns") or [])

    if payload.get("protected_columns") is not None:
        after = [str(c) for c in payload["protected_columns"]]
    else:
        col = payload.get("column") or payload.get("value")
        if not col:
            return []
        if col in before:
            return []  # already protected - no-op
        after = before + [str(col)]

    if after == before:
        return []

    config["protected_columns"] = after
    run.fairness_config = config

    return [
        StrategyDiff(
            field_path="fairness_config.protected_columns",
            before=before or None,
            after=after,
            summary=f"Protected attributes: {before or '[]'} → {after}",
            run_id=run.id,
        )
    ]


@_register("target")
async def _target_mutator(
    session: AsyncSession, run: Run, payload: dict[str, Any]
) -> list[StrategyDiff]:
    """Override target-level hygiene: which labels to drop, and binary collapse.

    Accepts:
      - {"drop_labels": ["unknown", ...]}     → rows with these target values dropped
      - {"positive_labels": ["high", ...]}    → collapse to binary (these → 1)
    drop_labels are UNIONed with any existing config (additive); positive_labels
    replace the collapse spec. Creates target_strategy if absent, so the user can
    set it before EDA has derived one. The override re-runs the pipeline from EDA
    (see analysis_task._OVERRIDE_RECOMPUTE_STEP) so profiling/task_type refresh.
    """
    config = dict(run.target_strategy or {})
    before_drop = [str(v) for v in (config.get("drop_labels") or [])]
    before_pos = [str(v) for v in (config.get("positive_labels") or [])]

    # drop_labels are additive (union); positive_labels replace the collapse spec.
    drop_labels = list(before_drop)
    new_drop = payload.get("drop_labels")
    if isinstance(new_drop, list):
        for v in new_drop:
            if v and str(v) not in drop_labels:
                drop_labels.append(str(v))

    positive_labels = before_pos
    if isinstance(payload.get("positive_labels"), list):
        positive_labels = [str(v) for v in payload["positive_labels"] if v]

    diffs: list[StrategyDiff] = []
    if drop_labels != before_drop:
        diffs.append(StrategyDiff(
            field_path="target_strategy.drop_labels",
            before=before_drop or None,
            after=drop_labels,
            summary=f"Drop unlabelled target rows: {drop_labels}",
            run_id=run.id,
        ))
    if positive_labels != before_pos:
        diffs.append(StrategyDiff(
            field_path="target_strategy.positive_labels",
            before=before_pos or None,
            after=positive_labels,
            summary=f"Collapse target to binary; positive = {positive_labels}",
            run_id=run.id,
        ))

    if not diffs:
        return []

    config["drop_labels"] = drop_labels
    config["positive_labels"] = positive_labels
    run.target_strategy = config
    return diffs


# ── Interrupt semantics (§2, B6) ──────────────────────────────────────────────

_EXPENSIVE_STEPS = frozenset({"training", "tuning", "calibration", "shap", "similarity"})


async def queue_intent_if_busy(
    session: AsyncSession,
    run: Run,
    intent: ChatIntent,
) -> bool:
    """Queue a modify intent if the pipeline is in an expensive step.

    Returns True when the intent was queued (pipeline is busy), False when the
    caller should apply it immediately via apply_intent_to_strategy.
    """
    if run.status != "running" or run.current_step not in _EXPENSIVE_STEPS:
        return False

    pending = PendingIntent(
        intent=intent,
        step_at_queue_time=run.current_step or "unknown",
    )
    current_queue: list = list(run.pending_intents or [])
    current_queue.append(pending.to_dict())
    run.pending_intents = current_queue
    session.add(run)

    await audit.append(
        session,
        run_id=run.id,
        actor="user",
        category=intent.category,
        action="intent_queued",
        payload={
            "intent_category": intent.category,
            "step_at_queue_time": run.current_step,
            "queue_depth": len(current_queue),
        },
        reason=f"Intent queued while {run.current_step} was running",
    )
    await session.commit()
    return True


async def flush_pending_intents(
    session: AsyncSession,
    run: Run,
) -> list[StrategyDiff]:
    """Apply all queued intents in order. Call after an expensive step completes.

    Called by the analysis task at each checkpoint so changes requested during
    heavy computation are visible before the user reviews the checkpoint card.
    """
    raw_queue: list = list(run.pending_intents or [])
    if not raw_queue:
        return []

    all_diffs: list[StrategyDiff] = []
    for raw in raw_queue:
        try:
            pending = PendingIntent.from_dict(raw)
            diffs = await apply_intent_to_strategy(session, run, pending.intent)
            all_diffs.extend(diffs)
        except Exception as exc:
            logger.warning("Failed to apply queued intent: %s - %s", raw, exc)

    run.pending_intents = []
    session.add(run)
    await session.commit()

    if all_diffs:
        logger.info(
            "Flushed %d pending intent(s) for run %s → %d diffs",
            len(raw_queue), run.id, len(all_diffs),
        )
    return all_diffs


# ── Dispatch ───────────────────────────────────────────────────────────────────

# The intent classifier sometimes labels a *modify* with the question-form
# category (e.g. "equity_query" for "add age to protected attributes"). Map these
# to the canonical decision category so the override still reaches a mutator.
_CATEGORY_ALIASES = {
    "equity_query": "fairness",
    "fairness_query": "fairness",
    "threshold_query": "threshold",
    "cost_matrix": "threshold",
    "model": "model_selection",
    "model_query": "model_selection",
    "preprocessing_query": "preprocessing",
    "target_query": "target",
    "label": "target",
}


def canonical_category(category: str) -> str:
    """Resolve a possibly question-form category to its decision category."""
    return _CATEGORY_ALIASES.get(category, category)


_DROP_VALUES = frozenset({"drop", "remove", "exclude", "delete"})


def extract_drop_columns(payload: dict[str, Any]) -> list[str]:
    """Pull the columns a preprocessing override asks to drop, multi-column aware.

    Reads three shapes so "drop both clinical_syndrome and clade" is never reduced
    to a single column the way a one-slot payload would:
      - {"columns_to_drop": ["a", "b"]}                      (explicit hint)
      - {"columns": ["a", "b"], "field": "action", "value": "drop"}
      - {"column": "a", "field": "action", "value": "drop"}  (single, legacy)
    Order-preserving and de-duplicated. Used only as a deterministic backstop so a
    clinician's explicit drop is guaranteed even if the agent under-complies.
    """
    cols: list[str] = []

    explicit = payload.get("columns_to_drop")
    if isinstance(explicit, list):
        cols.extend(str(c) for c in explicit if c)

    field = str(payload.get("field") or "").strip().lower()
    value = str(payload.get("value") or "").strip().lower()
    is_drop = field == "action" and value in _DROP_VALUES

    if is_drop:
        if isinstance(payload.get("columns"), list):
            cols.extend(str(c) for c in payload["columns"] if c)
        if payload.get("column"):
            cols.append(str(payload["column"]))

    seen: set[str] = set()
    out: list[str] = []
    for c in cols:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


async def record_directive(
    session: AsyncSession,
    run: Run,
    intent: ChatIntent,
) -> list[StrategyDiff]:
    """Record a verbatim human override as a directive on the run and audit it.

    The directive is appended to run.user_directives[category]; the producing
    step replays every directive for its category into the agent prompt when it
    re-runs, so the AI adjusts its decision to the human's instruction. Returns a
    single StrategyDiff so the chat UI shows the override and the router triggers
    the producer re-run (which keys off a non-empty diff list).
    """
    category = canonical_category(intent.category)
    instruction = (intent.reasoning or "").strip()
    payload = intent.structured_payload or {}
    # Prefer the user's own phrasing carried on the payload; fall back to reasoning.
    instruction = str(payload.get("instruction") or instruction).strip()
    if not instruction:
        return []

    directive = UserDirective(
        category=category,
        instruction=instruction,
        columns_to_drop=extract_drop_columns(payload),
    )

    directives = dict(run.user_directives or {})
    current: list = list(directives.get(category) or [])
    current.append(directive.to_dict())
    directives[category] = current
    run.user_directives = directives
    session.add(run)

    await audit.append(
        session,
        run_id=run.id,
        actor="user",
        category=category,
        action="directive_recorded",
        payload={
            "instruction": directive.instruction,
            "columns_to_drop": directive.columns_to_drop,
            "directive_count": len(current),
            "confidence": intent.confidence,
        },
        reason=f"Human override recorded for {category}: {directive.instruction}",
    )
    await session.commit()

    return _directive_diffs(run, directive)


def _directive_diffs(run: Run, directive: UserDirective) -> list[StrategyDiff]:
    """Build the diff cards shown for a recorded directive.

    For a preprocessing drop we emit one card per column ("action: keep → drop"),
    reading the column's current action as the "before" value, so the canvas shows
    exactly which features will be removed. The drop is realised when the producing
    step re-runs (and guaranteed by the agent's drop backstop), so these cards are
    a faithful preview of the committed override - not a separate edit path.
    Falls back to one summary card for non-drop directives so the chat router still
    sees a non-empty diff list and triggers the producer re-run.
    """
    diffs: list[StrategyDiff] = []
    if directive.category == "preprocessing" and directive.columns_to_drop:
        cols = (run.preprocessing_strategy or {}).get("columns", {})
        for col in directive.columns_to_drop:
            entry = cols.get(col)
            before = entry.get("action") if isinstance(entry, dict) else None
            diffs.append(StrategyDiff(
                field_path=f"preprocessing.columns.{col}.action",
                before=before,
                after="drop",
                summary=f"Drop {col} per your override: {before or '—'} → drop",
                run_id=run.id,
            ))
        return diffs

    return [
        StrategyDiff(
            field_path=f"user_directives.{directive.category}",
            before=None,
            after=directive.instruction,
            summary=f"Recorded your override for {directive.category}: {directive.instruction}",
            run_id=run.id,
        )
    ]


async def apply_intent_to_strategy(
    session: AsyncSession,
    run: Run,
    intent: ChatIntent,
) -> list[StrategyDiff]:
    """Dispatch intent to the appropriate mutator and commit atomically.

    Returns the list of StrategyDiff objects (may be empty if no change applies).
    """
    category = canonical_category(intent.category)

    # Producer-regenerated categories (e.g. preprocessing) are not edited field by
    # field - the override is recorded verbatim and replayed to the producing
    # agent when its step re-runs, so the AI adjusts its decision. This is what
    # lets a clinician override ANY preprocessing decision in plain language
    # (e.g. "drop both clinical_syndrome and clade") rather than one field at a time.
    if category in PRODUCER_REGENERATED_CATEGORIES:
        return await record_directive(session, run, intent)

    mutator = _MUTATORS.get(category)
    if mutator is None:
        return []

    diffs = await mutator(session, run, intent.structured_payload)

    if diffs:
        session.add(run)
        await audit.append(
            session,
            run_id=run.id,
            actor="user",
            category=category,
            action="strategy_override",
            payload={
                "diffs": [d.model_dump() for d in diffs],
                "intent_category": category,
                "confidence": intent.confidence,
            },
            reason=intent.reasoning,
        )
        await session.commit()

    return diffs
